export {
	defaultAge,
	defaultBMRAndExercise,
	defaultBMREquation,
	defaultCarbsGrams,
	defaultExerciseMultiplier,
	defaultFatsGrams,
	defaultGenre,
	defaultGoal,
	defaultHeight,
	defaultLBMFormula,
	defaultLbm,
	defaultProteinsGrams,
	defaultWeight,
} from '@macronutrients/core'
